[project]
name = "rand-spotify-playlist-generator"
version = "0.1.0"
description = "Create new playlists by selecting random songs from existing Spotify playlists"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "spotipy>=2.26.0",
]

authors = {name = "Huy Hong", email = "kevinhong.nl@gmail.com"}